version: '3.1'
services:
  kameleon:
    ports:
      - "8080:8080"
    build: ./
    container_name: kameleon
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_kameleooon:5432/main
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=main
    depends_on:
      - db_kameleooon
  db_kameleooon:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: db_kameleooon
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=main

