CREATE TABLE IF NOT EXISTS quotes (
                                      quote_id BIGINT GENERATED BY DEFAULT  AS IDENTITY NOT NULL,
                                      author BIGINT,
                                      quote varchar NOT NULL,
                                      create_time timestamp,
                                      rate BIGINT,
                                      CONSTRAINT pk_quote PRIMARY KEY (quote_id)
);

CREATE TABLE IF NOT EXISTS users (
                                       user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                       user_name VARCHAR(255) NOT NULL,
                                       email VARCHAR(512) NOT NULL,
                                       goodQuote BIGINT references  quotes (quote_id) ,
                                       badQuote BIGINT references  quotes (quote_id) ,
                                       CONSTRAINT pk_user PRIMARY KEY (user_id),
                                       CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS bad_quote(
                                          quote_id BIGINT  REFERENCES quotes (quote_id),
                                          user_id BIGINT  references users (user_id),
                                          CONSTRAINT pk_bad_quotes PRIMARY KEY (quote_id, user_id)
);
CREATE TABLE IF NOT EXISTS good_quote(
                                        quote_id BIGINT  REFERENCES quotes (quote_id),
                                        user_id BIGINT  references users (user_id),
                                        CONSTRAINT pk_good_quotes PRIMARY KEY (quote_id, user_id)
);





